/** Belgian road signs — official Dutch descriptions */

const SIGNS_NL: Record<string, string> = {
  // A — Gevaar (Danger)
  'A1a': 'Gevaarlijke bocht naar links (de weg draait plotseling naar links)',
  'A1b': 'Gevaarlijke bocht naar rechts (de weg draait plotseling naar rechts)',
  'A1c': 'Opeenvolging van bochten, de eerste naar links (meerdere gevaarlijke bochten)',
  'A1d': 'Opeenvolging van bochten, de eerste naar rechts (meerdere gevaarlijke bochten)',
  'A3': 'Gevaarlijke daling (steile helling, gebruik je remmen)',
  'A5': 'Steile helling opwaarts (steile heuvel voor je)',
  'A7a': 'Versmalling van de rijbaan aan beide zijden (de weg wordt smaller)',
  'A7b': 'Versmalling van de rijbaan links',
  'A7c': 'Versmalling van de rijbaan rechts',
  'A9': 'Beweegbare brug (de brug kan opengaan om boten door te laten)',
  'A11': 'Uitweg op een kaai of oever (gevaar om in het water te vallen)',
  'A13': 'Uitholling of bult (natuurlijke hobbel op de weg)',
  'A14': 'Verkeersdrempel (kunstmatige hobbel om de snelheid te verminderen)',
  'A15': 'Gladde rijbaan (gevaar voor slippen bij nat weer)',
  'A17': 'Losliggende steenslag (kleine steentjes op de weg)',
  'A19': 'Vallende stenen (rotsen kunnen op de weg vallen)',
  'A21': 'Oversteekplaats voor voetgangers (voetgangers kunnen oversteken)',
  'A23': 'Plaats vaak bezocht door kinderen (school, speelplein in de buurt)',
  'A25': 'Oversteekplaats voor fietsers en bromfietsers (zij kunnen de weg oversteken)',
  'A27': 'Overstekend groot wild (herten, everzwijnen op de weg)',
  'A29': 'Overstekend vee (koeien, schapen op de weg)',
  'A31': 'Werken (wegenwerken aan de gang)',
  'A33': 'Verkeerslichten (er is een verkeerslicht verderop)',
  'A35': 'Laagvliegende vliegtuigen (geluid en luchtverplaatsing mogelijk)',
  'A37': 'Zijwind (gevaar om van de weg geblazen te worden)',
  'A39': 'Verkeer in beide richtingen (let op tegenliggers)',
  'A41': 'Overweg met slagbomen (spoorweg beschermd door slagbomen)',
  'A43': 'Overweg zonder slagbomen (spoorweg zonder bescherming, zeer gevaarlijk)',
  'A45': 'Overweg met één spoor (één enkele spoorlijn)',
  'A47': 'Overweg met meerdere sporen (twee of meer spoorlijnen)',
  'A49': 'Kruising met spoorlijn (tram of trein kan de weg kruisen)',
  'A50': 'Filegevaar (file waarschijnlijk voor je)',
  'A51': 'Niet-nader omschreven gevaar (onderbord geeft de aard van het gevaar aan)',

  // B — Voorrang (Priorité)
  'B1': 'Voorrang verlenen (laat voertuigen op de voorrangsweg voorgaan)',
  'B3': 'Aankondiging voorrang verlenen (bereid je voor, verderop moet je voorrang verlenen)',
  'B5': 'STOP (stop volledig en verleen voorrang)',
  'B7': 'Aankondiging STOP (bereid je voor, verderop is een STOP)',
  'B9': 'Voorrangsweg (je hebt voorrang op elk kruispunt)',
  'B11': 'Einde voorrangsweg (de voorrang van rechts geldt weer)',
  'B13': 'Aankondiging einde voorrangsweg (bereid je voor, de voorrang stopt verderop)',
  'B15': 'Voorrang op dit kruispunt (jij mag eerst)',
  'B15a': 'Voorrang op het kruispunt (schema toont de voorrangsrichting)',
  'B15b': 'Voorrang op het kruispunt (richtingsschema)',
  'B15c': 'Voorrang op het kruispunt (richtingsschema)',
  'B15d': 'Voorrang op het kruispunt (richtingsschema)',
  'B15e': 'Voorrang op het kruispunt (richtingsschema)',
  'B15f': 'Voorrang op het kruispunt (richtingsschema)',
  'B15g': 'Voorrang op het kruispunt (richtingsschema)',
  'B17': 'Voorrang van rechts (voertuigen van rechts gaan eerst)',
  'B19': 'Smalle doorgang — voorrang verlenen (laat tegenliggers voorgaan)',
  'B21': 'Smalle doorgang — jij hebt voorrang (tegenliggers laten je voorgaan)',

  // C — Verbod (Interdiction)
  'C1': 'Verboden richting (je mag deze straat niet inrijden)',
  'C3': 'Verboden toegang in beide richtingen (weg afgesloten voor alle verkeer)',
  'C5': 'Verboden voor auto\'s en vrachtwagens (motorvoertuigen met meer dan 2 wielen)',
  'C6': 'Verboden voor quads',
  'C7': 'Verboden voor motorfietsen',
  'C9': 'Verboden voor bromfietsen (scooters, brommers)',
  'C11': 'Verboden voor fietsen',
  'C13': 'Verboden voor bespannen voertuigen (paarden die een kar trekken)',
  'C15': 'Verboden voor ruiters (personen te paard)',
  'C17': 'Verboden voor handkarren (karren die met de hand geduwd worden)',
  'C19': 'Verboden voor voetgangers (verboden hier te lopen)',
  'C21': 'Maximaal toegelaten gewicht (verboden als je voertuig het aangegeven gewicht overschrijdt)',
  'C22': 'Verboden voor autobussen (touringcars)',
  'C23': 'Verboden voor vrachtwagens (voertuigen voor goederenvervoer)',
  'C24': 'Verboden voor voertuigen met gevaarlijke goederen',
  'C24a': 'Verboden voor gevaarlijke goederen (variant)',
  'C24b': 'Verboden bij vervoer van brandbare of explosieve stoffen',
  'C24c': 'Verboden bij vervoer van waterverontreinigende stoffen',
  'C25': 'Maximaal toegelaten lengte (verboden als voertuig te lang is)',
  'C27': 'Maximaal toegelaten breedte (verboden als voertuig te breed is)',
  'C29': 'Maximaal toegelaten hoogte (verboden als voertuig te hoog is, bv. lage brug)',
  'C31a': 'Verboden links af te slaan op het volgende kruispunt',
  'C31b': 'Verboden rechts af te slaan op het volgende kruispunt',
  'C33': 'Verboden te keren (je mag hier geen U-bocht maken)',
  'C35': 'Verboden in te halen (verboden een ander voertuig voorbij te rijden)',
  'C37': 'Einde inhaalverbod (je mag weer inhalen)',
  'C39': 'Inhaalverbod voor vrachtwagens (zware voertuigen > 3,5 t)',
  'C41': 'Einde inhaalverbod voor vrachtwagens',
  'C43': 'Maximumsnelheid (de aangegeven snelheid niet overschrijden)',
  'C45': 'Einde snelheidsbeperking (de vorige beperking geldt niet meer)',
  'C46': 'Einde van alle plaatselijke verboden (alles wordt weer normaal)',
  'C47': 'Tolpost (je moet stoppen en betalen)',
  'C5-C7': 'Verboden voor auto\'s, vrachtwagens en motorfietsen',
  'C9-C11': 'Verboden voor bromfietsen en fietsen',

  // D — Gebod (Obligation)
  'D1a': 'Verplicht rechtdoor (je moet rechtdoor rijden)',
  'D1c': 'Verplicht links afslaan (je moet links afslaan op het kruispunt)',
  'D1d': 'Verplicht rechts afslaan (je moet rechts afslaan op het kruispunt)',
  'D1e': 'Links voorbij het obstakel (rij links langs het eiland of de paal)',
  'D1f': 'Rechts voorbij het obstakel (rij rechts langs het eiland of de paal)',
  'D3a': 'Rechtdoor of rechts (je hebt de keuze tussen deze twee richtingen)',
  'D3b': 'Rechtdoor of links (je hebt de keuze tussen deze twee richtingen)',
  'D5': 'Rotonde (je moet de aangegeven rijrichting volgen)',
  'D7': 'Verplicht fietspad (fietsers moeten hier rijden, niet op de rijbaan)',
  'D9a': 'Gescheiden pad voetgangers / fietsers (verticale lijn in het midden, ieder zijn kant)',
  'D9b': 'Gescheiden pad voetgangers / fietsers (zijden omgekeerd t.o.v. D9a)',
  'D10': 'Pad voorbehouden voor voetgangers en fietsers (gedeeld gebruik)',
  'D11': 'Verplicht pad voor voetgangers (voetgangers moeten hier lopen)',
  'D13': 'Verplicht pad voor ruiters (personen te paard)',

  // E — Parkeren (Stationnement)
  'E1': 'Parkeren toegestaan (witte P op blauw, je mag hier parkeren)',
  'E3': 'Halfmaandelijks wisselend parkeren (P met data 1-15 / 16-31, wissel van kant)',
  'E5': 'Blauwe zone — beperkt parkeren (gebruik je parkeerschijf)',
  'E7': 'Betalend parkeren (je moet betalen om te parkeren)',
  'E9a': 'Parking (plaats om je auto te parkeren)',
  'E9b': 'Park & Ride P+R (parkeer en neem het openbaar vervoer)',
  'E9c': 'Parkeren voorbehouden voor personen met een handicap',
  'STAT_INTERDIT': 'Parkeerverbod (blauwe cirkel met rode diagonale streep)',
  'ARRET_STAT_INTERDIT': 'Stilstaan en parkeren verboden (blauwe cirkel met rood kruis)',

  // F — Informatie (Information)
  'F1': 'Begin bebouwde kom (je rijdt een stad of dorp binnen, max 50 km/u)',
  'F1bh': 'Begin bebouwde kom met silhouet van monumenten (max 50 km/u)',
  'F3': 'Einde bebouwde kom (je verlaat de stad, de snelheidslimiet verandert)',
  'F3bh': 'Einde bebouwde kom met silhouet van monumenten',
  'F4a': 'Begin zone 30 (snelheid beperkt tot 30 km/u, woonwijk)',
  'F4b': 'Einde zone 30 (de limiet van 30 km/u geldt niet meer)',
  'F5': 'Begin autosnelweg (max 120 km/u, geen voetgangers of fietsers)',
  'F7': 'Einde autosnelweg (de autosnelwegregels gelden niet meer)',
  'F8': 'Tunnel (schakel je dimlichten in)',
  'F9': 'Weg voor auto\'s (zoals een autosnelweg maar max 120 km/u)',
  'F11': 'Einde weg voor auto\'s',
  'F12a': 'Woonerf (voetgangers hebben voorrang, max 20 km/u)',
  'F12b': 'Einde woonerf',
  'F13': 'Voorsorteerstroken (pijlen op het wegdek om je rijstrook te kiezen)',
  'F14': 'Fietsopstelstrook (zone voor fietsers voor het verkeerslicht)',
  'F17': 'Busstrook (rijstrook voorbehouden voor bussen en taxi\'s)',
  'F18': 'Vrije busbaan en tram (rijstrook voorbehouden voor openbaar vervoer)',
  'F19': 'Eenrichtingsverkeer (alle voertuigen rijden in dezelfde richting)',
  'F21': 'Rechts of links voorbijrijden (rij langs het obstakel aan beide kanten)',
  'F23a': 'Nummer van de rijksweg',
  'F45': 'Doodlopende weg (straat zonder uitweg)',
  'F45b': 'Doodlopende weg behalve voor voetgangers en fietsers (zij mogen door)',
  'F47': 'Einde werken (de werkzone is beëindigd)',
  'F111': 'Begin fietszone (de fiets heeft voorrang op de auto)',
  'F113': 'Einde fietszone',
  'F52': 'Nooduitgang in een tunnel (in geval van nood)',
  'F53': 'Ziekenhuis in de buurt (medische instelling)',
  'F55': 'Hulppost (eerste hulp beschikbaar)',
  'F56': 'Brandblusser (beschikbaar bij brand, vaak in tunnels)',
  'F59': 'Parking (plaats om je voertuig te parkeren)',
  'F60': 'Overdekte parking (binnenparking, meerdere verdiepingen)',
  'F62': 'Noodtelefoon (noodoproep, vaak op de autosnelweg)',
  'F63': 'Tankstation (brandstof beschikbaar)',
  'F65': 'Hotel of motel in de buurt',
  'F67': 'Restaurant in de buurt',
  'F71': 'Kampeerterrein (tenten toegelaten)',
  'F73': 'Terrein voor caravans en kampeerwagens',
  'F75': 'Jeugdherberg',
  'F77': 'Dienst voor toerisme (toeristische informatie)',
  'F79': 'Vermindering van het aantal rijstroken (een rijstrook eindigt, voeg in)',
  'F83': 'Oversteek van de middenberm (je rijdt tijdelijk aan de andere kant)',
  'F85': 'Tijdelijk verkeer in beide richtingen (let op tegenliggers)',
  'F87': 'Verkeersdrempel (Berlijns kussen of kunstmatige drempel)',
  'F99a': 'Pad voorbehouden voor voetgangers, fietsers en ruiters',
  'F101a': 'Einde pad voorbehouden voor voetgangers, fietsers en ruiters',
  'F103': 'Begin voetgangerszone (voorbehouden voor voetgangers, voertuigen verboden)',
  'F105': 'Einde voetgangerszone',
  'F117': 'Lage-emissiezone — LEZ (vervuilende voertuigen verboden)',
  'F118': 'Einde lage-emissiezone',

  // M — Aanvullend (Additionnels)
  'B22': 'Fietsers: rechts afslaan bij rood licht toegelaten (bord onder het licht)',
  'B23': 'Fietsers: rechtdoor bij rood licht toegelaten (bord onder het licht)',
  'M1': 'Onderbord: alleen voor fietsers',
  'M2': 'Onderbord: uitgezonderd fietsen (fietsen zijn niet betrokken)',
  'M3': 'Uitgezonderd fietsen en bromfietsen klasse A (max 25 km/u)',
  'M3bis': 'Uitgezonderd fietsen en alle bromfietsen',
  'M4': 'Fietsers toegelaten in beide richtingen (ook in eenrichtingsstraat)',
  'M5': 'Bromfietsen klasse A toegelaten in beide richtingen',
  'M5bis': 'Bromfietsen klasse A en B toegelaten in beide richtingen',
  'M6': 'Bromfietsen klasse B moeten deze rijstrook gebruiken',
  'M7': 'Verboden voor bromfietsen klasse B (max 45 km/u)',
  'M8': 'Rijstrook voorbehouden voor fietsen en bromfietsen',
  'M9': 'Fietsers toegelaten in beide richtingen op het kruispunt',
  'M10': 'Fietsen en bromfietsen toegelaten in beide richtingen',
  'M11': 'Uitgezonderd fietsen en bromfietsen (zij zijn niet betrokken)',
  'M12': 'Uitgezonderd fietsers en bromfietsen klasse A',
  'M13': 'Bromfietsen moeten deze rijstrook gebruiken',
  'M14': 'Tweewielers klasse B moeten deze rijstrook gebruiken',
  'M15': 'Verboden voor bromfietsen',
  'M16': 'Verboden voor bromfietsen klasse B',
  'M17': 'Fietsers en bromfietsen toegelaten in beide richtingen',
  'M18': 'Fietsers en bromfietsen klasse A in beide richtingen',
  'M19': 'Rijstrook voorbehouden voor bromfietsen',
  'M20': 'Rijstrook voorbehouden voor fietsen en bromfietsen',
  'M21': 'Voorbehouden voor steps en voortbewegingstoestellen',
  'M22': 'Uitgezonderd steps en voortbewegingstoestellen',
  'M23': 'Uitgezonderd fietsen en steps',
  'M24': 'Voorbehouden voor fietsen en steps',

  // FEU — Verkeerslichten (Feux)
  'FEU_TRICOLORE': 'Verkeerslichten (rood, oranje, groen)',
  'FEU_ROUGE': 'Rood licht (stop voor de stopstreep)',
  'FEU_ORANGE': 'Oranje licht (stop tenzij je niet meer veilig kunt stoppen)',
  'FEU_VERT': 'Groen licht (je mag doorrijden als de weg vrij is)',
  'FEU_CLIGNOTANT': 'Knipperend oranje licht (voorzichtig, het licht werkt niet normaal)',
  'FEU_FLECHE_VERTE': 'Groene pijl (doorgang alleen toegelaten in de richting van de pijl)',
  'FEU_PIETON_ROUGE': 'Rood voetgangerslicht (niet oversteken, wacht op groen)',
  'FEU_PIETON_VERT': 'Groen voetgangerslicht (je mag oversteken, maar blijf opletten)',
  'FEU_VELO_ROUGE': 'Rood fietslicht (fietsers moeten stoppen)',
  'FEU_VELO_VERT': 'Groen fietslicht (fietsers mogen doorrijden)',
  'CROIX_ROUGE_VOIE': 'Rood kruis op rijstrook (deze rijstrook is verboden)',
  'FLECHE_VERTE_VOIE': 'Groene pijl op rijstrook (deze rijstrook is toegelaten)',
  'FEU_TRAM': 'Licht voor tram (signaal voorbehouden voor trambestuurders)',

  // LIGNE — Wegmarkering (Marquage au sol)
  'LIGNE_CONTINUE': 'Doorgetrokken witte streep (verboden te overschrijden of in te halen)',
  'LIGNE_DISCONTINUE': 'Onderbroken witte streep (je mag ze overschrijden om in te halen)',
  'DOUBLE_CONTINUE': 'Dubbele doorgetrokken streep (verboden te overschrijden in beide richtingen)',
  'LIGNE_MIXTE': 'Gemengde streep (overschrijden alleen toegelaten aan de onderbroken kant)',
  'MARQUAGE_STOP': 'STOP-streep op het wegdek (stop voor deze lijn)',
  'MARQUAGE_CEDEZ': 'Driehoek op het wegdek (voorrang verlenen, laat anderen voorgaan)',
  'ZEBRAS': 'Oversteekplaats voor voetgangers — zebrapad (witte strepen, voetgangers hebben voorrang)',
  'CHEVRONS': 'Schuine strepen (gearceerde zone, verboden voor verkeer)',
  'DAMIER': 'Dambordmarkering (bufferzone tussen twee rijstroken, niet berijden)',

  // LT — Controlelampjes (Témoins phares)
  'TEMOIN_VEILLEUSES': 'Standlichten — stadslichten (minimale verlichting, \'s nachts in de stad)',
  'TEMOIN_CROISEMENT': 'Dimlichten — kruislichten (normale verlichting, verblinden niet)',
  'TEMOIN_ROUTE': 'Groot licht — koplampen (vol vermogen, buiten de bebouwde kom zonder verkeer)',
  'TEMOIN_BROUILLARD_AVANT': 'Mistlicht voor (aan te zetten bij mist, zware regen of sneeuw)',
};

export default SIGNS_NL;
