/** All Belgian road signs — official descriptions (Arrêté royal du 1er décembre 1975) */

export interface SignDef {
  code: string;
  name: string;
}

export const SIGNS_BY_CATEGORY: Record<string, SignDef[]> = {
  A: [
    { code: 'A1a', name: 'Virage dangereux à gauche (la route tourne brusquement vers la gauche)' },
    { code: 'A1b', name: 'Virage dangereux à droite (la route tourne brusquement vers la droite)' },
    { code: 'A1c', name: 'Succession de virages, le premier à gauche (plusieurs courbes dangereuses)' },
    { code: 'A1d', name: 'Succession de virages, le premier à droite (plusieurs courbes dangereuses)' },
    { code: 'A3', name: 'Descente dangereuse (pente raide, utilisez vos freins)' },
    { code: 'A5', name: 'Montée à forte inclinaison (côte raide devant vous)' },
    { code: 'A7a', name: 'Rétrécissement de la chaussée des deux côtés (la route devient plus étroite)' },
    { code: 'A7b', name: 'Rétrécissement de la chaussée par la gauche' },
    { code: 'A7c', name: 'Rétrécissement de la chaussée par la droite' },
    { code: 'A9', name: 'Pont mobile (le pont peut s\'ouvrir pour laisser passer les bateaux)' },
    { code: 'A11', name: 'Débouché sur un quai ou une berge (risque de chute dans l\'eau)' },
    { code: 'A13', name: 'Cassis ou dos-d\'âne (bosse naturelle sur la route)' },
    { code: 'A14', name: 'Ralentisseur (bosse artificielle pour réduire la vitesse)' },
    { code: 'A15', name: 'Chaussée glissante (risque de dérapage par temps humide)' },
    { code: 'A17', name: 'Projection de gravillons (petits cailloux sur la route)' },
    { code: 'A19', name: 'Chutes de pierres (des rochers peuvent tomber sur la route)' },
    { code: 'A21', name: 'Passage pour piétons (des piétons peuvent traverser)' },
    { code: 'A23', name: 'Endroit fréquenté par des enfants (école, plaine de jeux à proximité)' },
    { code: 'A25', name: 'Passage de cyclistes et cyclomoteurs (ils peuvent traverser la route)' },
    { code: 'A27', name: 'Traversée de gros gibier (cerfs, sangliers sur la route)' },
    { code: 'A29', name: 'Traversée de bétail (vaches, moutons sur la route)' },
    { code: 'A31', name: 'Travaux (chantier en cours sur la route)' },
    { code: 'A33', name: 'Signaux lumineux (un feu de circulation se trouve plus loin)' },
    { code: 'A35', name: 'Survol d\'avions à basse altitude (bruit et souffle possibles)' },
    { code: 'A37', name: 'Vent latéral (risque de déportation par le vent)' },
    { code: 'A39', name: 'Circulation dans les deux sens (attention aux véhicules en sens inverse)' },
    { code: 'A41', name: 'Passage à niveau avec barrières (voie ferrée protégée par des barrières)' },
    { code: 'A43', name: 'Passage à niveau sans barrières (voie ferrée sans protection, très dangereux)' },
    { code: 'A45', name: 'Passage à niveau à voie unique (une seule voie ferrée)' },
    { code: 'A47', name: 'Passage à niveau à plusieurs voies (deux ou plus voies ferrées)' },
    { code: 'A49', name: 'Croisement avec voie ferrée (tramway ou train peut croiser la route)' },
    { code: 'A50', name: 'Risque de file (embouteillage probable devant vous)' },
    { code: 'A51', name: 'Danger non précisé (panneau additionnel indique la nature du danger)' },
  ],
  B: [
    { code: 'B1', name: 'Cédez le passage (laissez passer les véhicules sur la route prioritaire)' },
    { code: 'B3', name: 'Annonce d\'un cédez le passage (préparez-vous, un cédez le passage arrive plus loin)' },
    { code: 'B5', name: 'STOP (arrêtez-vous complètement et cédez le passage)' },
    { code: 'B7', name: 'Annonce d\'un STOP (préparez-vous, un STOP arrive plus loin)' },
    { code: 'B9', name: 'Route prioritaire (vous avez la priorité à chaque carrefour)' },
    { code: 'B11', name: 'Fin de route prioritaire (la priorité de droite reprend)' },
    { code: 'B13', name: 'Annonce de fin de route prioritaire (préparez-vous, la priorité s\'arrête plus loin)' },
    { code: 'B15', name: 'Priorité à cette intersection (vous passez en premier)' },
    { code: 'B15a', name: 'Priorité à l\'intersection (schéma montrant la direction prioritaire)' },
    { code: 'B15b', name: 'Priorité à l\'intersection (schéma directionnel)' },
    { code: 'B15c', name: 'Priorité à l\'intersection (schéma directionnel)' },
    { code: 'B15d', name: 'Priorité à l\'intersection (schéma directionnel)' },
    { code: 'B15e', name: 'Priorité à l\'intersection (schéma directionnel)' },
    { code: 'B15f', name: 'Priorité à l\'intersection (schéma directionnel)' },
    { code: 'B15g', name: 'Priorité à l\'intersection (schéma directionnel)' },
    { code: 'B17', name: 'Priorité de droite (les véhicules venant de droite passent en premier)' },
    { code: 'B19', name: 'Passage étroit — cédez le passage (laissez passer ceux d\'en face)' },
    { code: 'B21', name: 'Passage étroit — vous avez la priorité (ceux d\'en face vous laissent passer)' },
  ],
  C: [
    { code: 'C1', name: 'Sens interdit (vous ne pouvez pas entrer dans cette rue)' },
    { code: 'C3', name: 'Accès interdit dans les deux sens (route fermée à toute circulation)' },
    { code: 'C5', name: 'Interdit aux voitures et camions (véhicules à moteur à plus de 2 roues)' },
    { code: 'C6', name: 'Interdit aux quads' },
    { code: 'C7', name: 'Interdit aux motos (motocyclettes)' },
    { code: 'C9', name: 'Interdit aux cyclomoteurs (scooters, mobylettes)' },
    { code: 'C11', name: 'Interdit aux vélos (bicyclettes)' },
    { code: 'C13', name: 'Interdit aux véhicules attelés (chevaux tirant une charrette)' },
    { code: 'C15', name: 'Interdit aux cavaliers (personnes à cheval)' },
    { code: 'C17', name: 'Interdit aux charrettes à bras (chariots poussés à la main)' },
    { code: 'C19', name: 'Interdit aux piétons (défense de marcher ici)' },
    { code: 'C21', name: 'Poids maximum autorisé (interdit si votre véhicule dépasse le poids indiqué)' },
    { code: 'C22', name: 'Interdit aux autocars (bus de tourisme)' },
    { code: 'C23', name: 'Interdit aux camions (véhicules de transport de marchandises)' },
    { code: 'C24', name: 'Interdit aux véhicules transportant des marchandises dangereuses' },
    { code: 'C24a', name: 'Interdit aux marchandises dangereuses (variante)' },
    { code: 'C24b', name: 'Interdit si transport de matières inflammables ou explosives' },
    { code: 'C24c', name: 'Interdit si transport de matières polluant les eaux' },
    { code: 'C25', name: 'Longueur maximale autorisée (interdit si véhicule trop long)' },
    { code: 'C27', name: 'Largeur maximale autorisée (interdit si véhicule trop large)' },
    { code: 'C29', name: 'Hauteur maximale autorisée (interdit si véhicule trop haut, ex : pont bas)' },
    { code: 'C31a', name: 'Interdiction de tourner à gauche au prochain carrefour' },
    { code: 'C31b', name: 'Interdiction de tourner à droite au prochain carrefour' },
    { code: 'C33', name: 'Demi-tour interdit (vous ne pouvez pas faire demi-tour ici)' },
    { code: 'C35', name: 'Dépassement interdit (défense de doubler un autre véhicule)' },
    { code: 'C37', name: 'Fin d\'interdiction de dépassement (vous pouvez à nouveau doubler)' },
    { code: 'C39', name: 'Dépassement interdit pour les camions (poids lourds > 3,5 t)' },
    { code: 'C41', name: 'Fin d\'interdiction de dépassement pour les camions' },
    { code: 'C43', name: 'Vitesse maximale autorisée (ne pas dépasser la vitesse indiquée)' },
    { code: 'C45', name: 'Fin de limitation de vitesse (la limitation précédente ne s\'applique plus)' },
    { code: 'C46', name: 'Fin de toutes les interdictions locales (tout redevient normal)' },
    { code: 'C47', name: 'Poste de péage (vous devez vous arrêter et payer)' },
    { code: 'C5-C7', name: 'Interdit aux voitures, camions et motos' },
    { code: 'C9-C11', name: 'Interdit aux cyclomoteurs et vélos' },
  ],
  D: [
    { code: 'D1a', name: 'Tout droit obligatoire (vous devez continuer tout droit)' },
    { code: 'D1c', name: 'Tourner à gauche obligatoire (vous devez tourner à gauche au carrefour)' },
    { code: 'D1d', name: 'Tourner à droite obligatoire (vous devez tourner à droite au carrefour)' },
    { code: 'D1e', name: 'Passer à gauche de l\'obstacle (contournez l\'île ou le poteau par la gauche)' },
    { code: 'D1f', name: 'Passer à droite de l\'obstacle (contournez l\'île ou le poteau par la droite)' },
    { code: 'D3a', name: 'Tout droit ou à droite (vous avez le choix entre ces deux directions)' },
    { code: 'D3b', name: 'Tout droit ou à gauche (vous avez le choix entre ces deux directions)' },
    { code: 'D5', name: 'Rond-point (vous devez suivre le sens giratoire indiqué par les flèches)' },
    { code: 'D7', name: 'Piste cyclable obligatoire (les cyclistes doivent rouler ici, pas sur la route)' },
    { code: 'D9a', name: 'Chemin séparé piétons / cyclistes (ligne verticale au milieu, chacun son côté)' },
    { code: 'D9b', name: 'Chemin séparé piétons / cyclistes (côtés inversés par rapport au D9a)' },
    { code: 'D10', name: 'Chemin réservé aux piétons et cyclistes (usage partagé)' },
    { code: 'D11', name: 'Chemin obligatoire pour piétons (les piétons doivent marcher ici)' },
    { code: 'D13', name: 'Chemin obligatoire pour cavaliers (personnes à cheval)' },
  ],
  E: [
    { code: 'E1', name: 'Stationnement autorisé (P blanc sur fond bleu, vous pouvez vous garer ici)' },
    { code: 'E3', name: 'Stationnement alterné semi-mensuel (P avec dates 1-15 / 16-31, changez de côté)' },
    { code: 'E5', name: 'Zone bleue — stationnement à durée limitée (utilisez votre disque de stationnement)' },
    { code: 'E7', name: 'Stationnement payant (vous devez payer pour vous garer)' },
    { code: 'E9a', name: 'Parking (emplacement pour garer votre voiture)' },
    { code: 'E9b', name: 'Parking relais P+R (garez-vous et prenez les transports en commun)' },
    { code: 'E9c', name: 'Stationnement réservé aux personnes handicapées' },
    { code: 'STAT_INTERDIT', name: 'Stationnement interdit (cercle bleu avec barre rouge diagonale)' },
    { code: 'ARRET_STAT_INTERDIT', name: 'Arrêt et stationnement interdits (cercle bleu avec croix rouge)' },
  ],
  F: [
    { code: 'F1', name: 'Début d\'agglomération (vous entrez dans une ville ou un village, max 50 km/h)' },
    { code: 'F1bh', name: 'Début d\'agglomération avec silhouette de monuments (max 50 km/h)' },
    { code: 'F3', name: 'Fin d\'agglomération (vous quittez la ville, la limite de vitesse change)' },
    { code: 'F3bh', name: 'Fin d\'agglomération avec silhouette de monuments' },
    { code: 'F4a', name: 'Début de zone 30 (vitesse limitée à 30 km/h, quartier résidentiel)' },
    { code: 'F4b', name: 'Fin de zone 30 (la limite de 30 km/h ne s\'applique plus)' },
    { code: 'F5', name: 'Début d\'autoroute (vitesse max 120 km/h, pas de piétons ni vélos)' },
    { code: 'F7', name: 'Fin d\'autoroute (les règles d\'autoroute ne s\'appliquent plus)' },
    { code: 'F8', name: 'Tunnel (allumez vos feux de croisement)' },
    { code: 'F9', name: 'Route pour automobiles (comme une autoroute mais max 120 km/h)' },
    { code: 'F11', name: 'Fin de route pour automobiles' },
    { code: 'F12a', name: 'Zone résidentielle (piétons prioritaires, max 20 km/h)' },
    { code: 'F12b', name: 'Fin de zone résidentielle' },
    { code: 'F13', name: 'Présélection de voies (flèches au sol pour choisir votre bande)' },
    { code: 'F14', name: 'Sas vélo (zone avancée pour cyclistes devant le feu)' },
    { code: 'F17', name: 'Bande bus (voie réservée aux autobus et taxis)' },
    { code: 'F18', name: 'Site propre bus et tram (voie réservée aux transports en commun)' },
    { code: 'F19', name: 'Sens unique (tous les véhicules roulent dans le même sens)' },
    { code: 'F21', name: 'Passer à droite ou à gauche (contournez l\'obstacle de chaque côté)' },
    { code: 'F23a', name: 'Numéro de route nationale' },
    { code: 'F45', name: 'Voie sans issue (rue en cul-de-sac, pas de sortie)' },
    { code: 'F45b', name: 'Voie sans issue sauf piétons et cyclistes (ils peuvent passer)' },
    { code: 'F47', name: 'Fin des travaux (la zone de chantier est terminée)' },
    { code: 'F111', name: 'Début de zone cyclable (le vélo a la priorité sur la voiture)' },
    { code: 'F113', name: 'Fin de zone cyclable' },
    { code: 'F52', name: 'Sortie de secours dans un tunnel (en cas d\'urgence)' },
    { code: 'F53', name: 'Hôpital à proximité (établissement sanitaire)' },
    { code: 'F55', name: 'Poste de secours (premiers soins disponibles)' },
    { code: 'F56', name: 'Extincteur (disponible en cas d\'incendie, souvent dans les tunnels)' },
    { code: 'F59', name: 'Parking (emplacement pour garer votre véhicule)' },
    { code: 'F60', name: 'Parking couvert (parking intérieur, à étages)' },
    { code: 'F62', name: 'Téléphone d\'urgence (appel de secours, souvent sur autoroute)' },
    { code: 'F63', name: 'Station-service (carburant disponible)' },
    { code: 'F65', name: 'Hôtel ou motel à proximité' },
    { code: 'F67', name: 'Restaurant à proximité' },
    { code: 'F71', name: 'Terrain de camping (tentes autorisées)' },
    { code: 'F73', name: 'Terrain pour caravanes et camping-cars' },
    { code: 'F75', name: 'Auberge de jeunesse' },
    { code: 'F77', name: 'Office de tourisme (informations touristiques)' },
    { code: 'F79', name: 'Réduction du nombre de bandes (une voie se termine, rabattez-vous)' },
    { code: 'F83', name: 'Traversée du terre-plein central (vous roulez temporairement de l\'autre côté)' },
    { code: 'F85', name: 'Circulation dans les deux sens temporaire (attention au trafic en face)' },
    { code: 'F87', name: 'Ralentisseur (coussin berlinois ou dos-d\'âne artificiel)' },
    { code: 'F99a', name: 'Chemin réservé aux piétons, cyclistes et cavaliers' },
    { code: 'F101a', name: 'Fin du chemin réservé aux piétons, cyclistes et cavaliers' },
    { code: 'F103', name: 'Début de zone piétonne (réservée aux piétons, véhicules interdits)' },
    { code: 'F105', name: 'Fin de zone piétonne' },
    { code: 'F117', name: 'Zone de basses émissions — LEZ (véhicules polluants interdits)' },
    { code: 'F118', name: 'Fin de zone de basses émissions' },
  ],
  M: [
    { code: 'B22', name: 'Cyclistes : tourner à droite au feu rouge autorisé (panneau sous le feu)' },
    { code: 'B23', name: 'Cyclistes : aller tout droit au feu rouge autorisé (panneau sous le feu)' },
    { code: 'M1', name: 'Panneau additionnel : uniquement pour les cyclistes' },
    { code: 'M2', name: 'Panneau additionnel : excepté vélos (les vélos ne sont pas concernés)' },
    { code: 'M3', name: 'Excepté bicyclettes et cyclomoteurs classe A (max 25 km/h)' },
    { code: 'M3bis', name: 'Excepté bicyclettes et tous les cyclomoteurs' },
    { code: 'M4', name: 'Cyclistes autorisés dans les deux sens (même en sens unique)' },
    { code: 'M5', name: 'Cyclomoteurs classe A autorisés dans les deux sens' },
    { code: 'M5bis', name: 'Cyclomoteurs classe A et B autorisés dans les deux sens' },
    { code: 'M6', name: 'Les cyclomoteurs classe B doivent emprunter cette voie' },
    { code: 'M7', name: 'Interdit aux cyclomoteurs classe B (max 45 km/h)' },
    { code: 'M8', name: 'Voie réservée aux vélos et cyclomoteurs uniquement' },
    { code: 'M9', name: 'Cyclistes autorisés dans les deux sens au carrefour' },
    { code: 'M10', name: 'Vélos et cyclomoteurs autorisés dans les deux sens' },
    { code: 'M11', name: 'Excepté bicyclettes et cyclomoteurs (ils ne sont pas concernés)' },
    { code: 'M12', name: 'Excepté cyclistes et cyclomoteurs classe A' },
    { code: 'M13', name: 'Les cyclomoteurs doivent emprunter cette voie' },
    { code: 'M14', name: 'Les deux roues classe B doivent emprunter cette voie' },
    { code: 'M15', name: 'Interdit aux cyclomoteurs' },
    { code: 'M16', name: 'Interdit aux cyclomoteurs classe B' },
    { code: 'M17', name: 'Cyclistes et cyclomoteurs autorisés dans les deux sens' },
    { code: 'M18', name: 'Cyclistes et cyclomoteurs classe A dans les deux sens' },
    { code: 'M19', name: 'Voie réservée aux cyclomoteurs uniquement' },
    { code: 'M20', name: 'Voie réservée aux vélos et cyclomoteurs' },
    { code: 'M21', name: 'Réservé aux trottinettes et engins de déplacement' },
    { code: 'M22', name: 'Excepté trottinettes et engins de déplacement' },
    { code: 'M23', name: 'Excepté vélos et trottinettes' },
    { code: 'M24', name: 'Réservé aux vélos et trottinettes' },
  ],
  FEU: [
    { code: 'FEU_TRICOLORE', name: 'Feux de circulation (rouge, orange, vert)' },
    { code: 'FEU_ROUGE', name: 'Feu rouge (arrêtez-vous avant la ligne d\'arrêt)' },
    { code: 'FEU_ORANGE', name: 'Feu orange (arrêtez-vous sauf si vous ne pouvez plus le faire en sécurité)' },
    { code: 'FEU_VERT', name: 'Feu vert (vous pouvez passer si la voie est libre)' },
    { code: 'FEU_CLIGNOTANT', name: 'Feu orange clignotant (prudence, le feu ne fonctionne pas normalement)' },
    { code: 'FEU_FLECHE_VERTE', name: 'Flèche verte (passage autorisé uniquement dans la direction de la flèche)' },
    { code: 'FEU_PIETON_ROUGE', name: 'Feu piéton rouge (ne traversez pas, attendez le vert)' },
    { code: 'FEU_PIETON_VERT', name: 'Feu piéton vert (vous pouvez traverser, mais restez vigilant)' },
    { code: 'FEU_VELO_ROUGE', name: 'Feu vélo rouge (les cyclistes doivent s\'arrêter)' },
    { code: 'FEU_VELO_VERT', name: 'Feu vélo vert (les cyclistes peuvent passer)' },
    { code: 'CROIX_ROUGE_VOIE', name: 'Croix rouge sur voie (cette bande de circulation est interdite)' },
    { code: 'FLECHE_VERTE_VOIE', name: 'Flèche verte sur voie (cette bande de circulation est autorisée)' },
    { code: 'FEU_TRAM', name: 'Feu pour tramway (signal réservé aux conducteurs de tram)' },
  ],
  LIGNE: [
    { code: 'LIGNE_CONTINUE', name: 'Ligne blanche continue (interdit de la franchir ou de dépasser)' },
    { code: 'LIGNE_DISCONTINUE', name: 'Ligne blanche discontinue (vous pouvez la franchir pour dépasser)' },
    { code: 'DOUBLE_CONTINUE', name: 'Double ligne continue (interdit de franchir dans les deux sens)' },
    { code: 'LIGNE_MIXTE', name: 'Ligne mixte (franchissement autorisé du côté discontinu uniquement)' },
    { code: 'MARQUAGE_STOP', name: 'Ligne STOP au sol (arrêtez-vous avant cette ligne)' },
    { code: 'MARQUAGE_CEDEZ', name: 'Triangle au sol (cédez le passage, laissez passer les autres)' },
    { code: 'ZEBRAS', name: 'Passage piétons — zèbres (bandes blanches, les piétons ont la priorité)' },
    { code: 'CHEVRONS', name: 'Chevrons (hachures, zone interdite à la circulation)' },
    { code: 'DAMIER', name: 'Damier (zone tampon entre deux voies, ne pas rouler dessus)' },
  ],
  LT: [
    { code: 'TEMOIN_VEILLEUSES', name: 'Feux de position — veilleuses (éclairage minimum, de nuit en ville)' },
    { code: 'TEMOIN_CROISEMENT', name: 'Feux de croisement — codes (éclairage normal, n\'éblouissent pas)' },
    { code: 'TEMOIN_ROUTE', name: 'Feux de route — phares (pleine puissance, hors agglomération sans trafic)' },
    { code: 'TEMOIN_BROUILLARD_AVANT', name: 'Antibrouillard avant (à allumer par brouillard, pluie forte ou neige)' },
  ],
};
